### PR TITLE
The package breaks code when used from NuGet

### PR DESCRIPTION
**Pull request by rastrup**
Fixes to correct what the package breaks

### CODE REVIEW

**Comment by robinhultman** [comment]
It would seem that these assemblies are not in GAC but rather in the BizTalk installation folder thus referencing them as a framework assembly won't have any effect. Not sure what would be the best way to do this.

**Comment by rastrup** [comment]
They should be in the GAC after a standard BizTalk installation (even only the SDK, i checked) and since BizTalk is required to do pipeline coding they should be in the GAC

**Comment by robinhultman** [comment]
You are right. I didn't get the references correctly in your PR either so that got me confused. It seems that you also need to specify targetFramework in the nuspec file:
`<frameworkAssembly assemblyName="Microsoft.BizTalk.GlobalPropertySchemas" targetFramework="net40"  />`

TargetFramework shouldn't be required but I didn't get the reference without it on my BTS 2013 machine?

You also need to add Microsoft.BizTalk.Pipeline to the reference list.

**Comment by robinhultman** [comment]
Great! Thanks!

**Pull request merged**
